# Server settings
server:
    port: 8087
# SPRING PROFILES
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/sgz?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
        username: root
        password: 111111
    freemarker:
        allow-request-override: false
        allow-session-override: false
        cache: false #缓存配置
        charset: UTF-8 #编码格式
        request-context-attribute: request # 访问request名称定义
        check-template-location: true
        content-type: text/html # 设置Content-Type
        enabled: true
        expose-request-attributes: false # 设定所有request的属性在merge到模板的时候，是否要都添加到model中
        expose-session-attributes: false # 是否在merge模板的时候，将HttpSession属性都添加到model中
        expose-spring-macro-helpers: true # 设定是否以springMacroRequestContext的形式暴露RequestContext给Spring’s macro library使用
        prefer-file-system-access: true
        suffix: .ftl
        template-loader-path: classpath:/templates/ #模板加载路径 按需配置
        settings:
            template_update_delay: 0
            default_encoding: UTF-8
            classic_compatible: true #解决前台使用${}赋值值为空的情况
    resources:
        static-locations: classpath:/static/
        chain:
            strategy:
                content:
                    enabled: true
                    paths: /**
logging:
    level:
        com.blackcat.dao: debug
